version: '3'

services:  
  php:
    image: php:7.3-fpm
    volumes: 
      - ./:/var/www
  nginx:
    image: nginx:1.19.1
    volumes: 
      - ./:/var/www
      - .docker/nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
    ports: 
      - "80:80"
      - "443:443"
  db:
    image: mysql:8
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456789
    volumes: 
      - dbdata:/var/lib/mysql/
  redis: 
    image: redis
    ports: 
      - "6379:6379"
    
volumes: 
  dbdata: 
    driver: local